### PR TITLE
FEATURE: Adding support for MAC OS + LLVM compiler

### PR DESCRIPTION
**Pull request by Scheremo**
This PR adds support for building and running GVSoC on Mac OS using the native LLVM/CLANG compiler toolchain.

### CODE REVIEW

**Review by haugoug — COMMENTED** [review]
The indentation is all messed-up can you rearrange it ?

**Comment by Scheremo** [comment]
> The indentation is all messed-up can you rearrange it ?

Is there some formatting guide / clang format config GVSoC follows? This would make matching it easier.

**Comment by Scheremo** [comment]
No worries, I will take care of it and let you know.
It might make sense to add a formating / linting configuration in the future, though.

**Comment by haugoug** [comment]
Yes sure !

**Comment by haugoug** [comment]
I've manually integrated your changes, let me know if there is any issue

**Pull request closed without merging**
